# Generated by Django 4.2.9 on 2024-02-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='place',
            new_name='Places',
        ),
    ]
