# Generated by Django 4.2.9 on 2024-02-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_rename_place_places'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
